[xmpp]
    [xmpp.myxmpp]
    Server="<DOMAINNAME>:5222"
    #Jid your userid
    Jid="<XMPP_USER>"
    Password="<XMPP_PASS>"
    Muc="conference.<DOMAINNAME>"
    Nick="xmppbot"
    RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[telegram]
    [telegram.mytelegram]
    Token="<TELEGRAM_TOKEN>"
    RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[[gateway]]
    name="<CHANNEL>"
    enable=true

    [[gateway.inout]]
    account="xmpp.myxmpp"
    channel="<CHANNEL>"

    [[gateway.inout]]
    account="telegram.mytelegram"
    channel="<TELEGRAM_CHANNEL>"
