[xmpp]
    [xmpp.main]
    Server="<DOMAINNAME>:5222"
    #Jid your userid
    Jid="<XMPP_USER>"
    Password="<XMPP_PASS>"
    Muc="conference.<DOMAINNAME>"
    Nick="ChatBridge"
    RemoteNickFormat="[{NICK}] "

[telegram]
    [telegram.main]
    Token="<TELEGRAM_TOKEN>"
    RemoteNickFormat="[{NICK}] "
    MessageFormat="HTMLNick"

[[gateway]]
    name="gateway1"
    enable=true

    [[gateway.inout]]
    account="xmpp.main"
    channel="<CHANNEL>"

    [[gateway.inout]]
    account="telegram.main"
    channel="<TELEGRAM_CHANNEL>"
