version: "2"
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs
    labels: 
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: ""
    networks:
      - nginx_prosody
      - nginx_portainer

  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - /data/configs/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro 
    volumes_from: 
      - nginx 
    labels: 
      com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen: ""
    depends_on:
      - nginx
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

#  -notify-sighup nginx -watch -wait 5s:30s \
#  /etc/docker-gen/templates/nginx.tmpl \
#  /etc/nginx/conf.d/default.conf


  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro  
    depends_on:
      - nginx-gen
    environment:
      ACME_CA_URI: https://acme-staging.api.letsencrypt.org/directory

# run portainer for administration
  portainer:
    image: portainer/portainer
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      VIRTUAL_HOST: "admin.${DOMAINNAME}"
      LETSENCRYPT_HOST: "admin.${DOMAINNAME}"
      LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"
    depends_on:
      - nginx-gen
      - nginx-letsencrypt
    networks:
      - nginx_portainer

  prosody:
    image: prosody/prosody
    container_name: prosody
    ports:
      - 5222:5222
      - 5269:5269
    volumes:
      - nginx_certs:/etc/prosody/certs:ro
      - /data/prosody:/data
      - /data/configs/prosody.cfg.lua:/etc/prosody/prosody.cfg.lua
    environment:
      VIRTUAL_HOST: "${DOMAINNAME}"
      VIRTUAL_PORT: "5280"
      LETSENCRYPT_HOST: "${DOMAINNAME}"
      LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"
    depends_on:
      - nginx-gen
      - nginx-letsencrypt
    networks:
      - nginx_prosody

networks:
  - nginx_prosody
  - nginx_portainer

volumes:
  portainer_data:
  nginx_certs:
  nginx_conf:
  nginx_vhost:
  nginx_html:
