version: "3"
services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs
    labels: 
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: ""

  nginx-gen:
    image: jwilder/docker-gen
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs
      - /data/configs/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro 
    labels: 
      com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen: ""
    depends_on:
      - nginx
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
#  -notify-sighup nginx -watch -wait 5s:30s \
#  /etc/docker-gen/templates/nginx.tmpl \
#  /etc/nginx/conf.d/default.conf


  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro  
    depends_on:
      - nginx

# run portainer for administration
  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      VIRTUAL_HOST: "admin.${DOMAINNAME:?domainname not set}"
      LETSENCRYPT_HOST: "admin.${$DOMAINNAME:?domainname not set}"
      LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL:?letsencrypt_email not set}"
    depends_on:
      - nginx-gen
      - nginx-letsencrypt

  prosody:
    image: prosody/prosody
    ports:
      - 5222:5222
      - 5269:5269
    volumes:
      - nginx_certs:/etc/prosody/certs:ro
      - /data/prosody:/data
      - /data/configs/prosody.cfg.lua:/etc/prosody/prosody.cfg.lua
    environment:
      VIRTUAL_HOST: "${DOMAINNAME:?domainname not set}"
      VIRTUAL_PORT: "5280"
      LETSENCRYPT_HOST: "${$DOMAINNAME:?domainname not set}"
      LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL:?letsencrypt_email not set}"
    depends_on:
      - nginx-gen
      - nginx-letsencrypt
  
      
volumes:
  portainer_data:
  nginx_certs:
  nginx_conf:
  nginx_vhost:
  nginx_html:
